name: Update README
# Source code: Clayton Hamilton https://github.com/claytonjhamilton

on:
  # push:      # run @ every push
  schedule:
    - cron: '0 9 * * *' 

# on:
#   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.14'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute main.py script 
        run: python main.py
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Auto update README"
          git push 